### ISSUE TITLE
[Feature Request] Custom filters

### ISSUE THREAD

**Issue by Anacondo** [porcino/Av1ador#12]
Please add the possibility to add new filters and/or edit the default ones. From what I can tell they're mostly hardcoded (re-sizing, tone mapping, audio processing, etc.) and I believe it would made sense to allow the user to modify them or at least define their own. Thanks a lot!

**Comment by porcino** [comment]
Check the nightly build, you can now save with right click in the filter list, later I'm going to add an option to attach a description to each of them

**Comment by Anacondo** [comment]
Thanks for the quick response! I'm getting a crash as soon as I click the "add filter" button, though:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Av1ador.Form1.FilteraddDropDownButton_DropDownOpening(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownShow(EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDown(Boolean mousePush)
   at System.Windows.Forms.ToolStripDropDownButton.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Av1ador.Program.Main()`

**Comment by Anacondo** [comment]
Filters menu seems to work now, but I get another crash as soon as I try to import a video:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Av1ador.Form1.Get_res(String entry_res)
   at Av1ador.Form1.Mpv_load_first()
   at Av1ador.Form1.AddfilesButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Av1ador.Program.Main()`

**Comment by porcino** [comment]
> I get another crash as soon as I try to import a video...

Fixed, that bug was old, it seems that I never encountered it because I always use drag and drop and that worked.

**Comment by Anacondo** [comment]
> Fixed, that bug was old, it seems that I never encountered it because I always use drag and drop and that worked.

Seems to work perfectly now, thanks a bunch! Any chance to be able to replace the default filters with these custom ones, or at least edit the defaults in some way?
